version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/app
    # command: sh -c "cd hello-vue && npm run serve"
    ports:
    - "8080:8080"